repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Keep the version for general utility hooks
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: examples/notebooks/
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: ^pyrelational/pyrelational
  - repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: isort --profile=black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: |
            (?x)(
                ^tests/ |
                ^examples/ |
                ^docs/
            )
        args: [
            --strict,
            --follow-imports=silent,
            --ignore-missing-imports,
            --allow-redefinition,
            --install-types,
            --non-interactive,
            --implicit-reexport,
            --allow-untyped-calls,
            --disable-error-code=no-redef,
        ]
