name: lint-task
# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
  
jobs:

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-lint-test:
    runs-on: ubuntu-latest
    permissions: write-all
    name: lint
    # Name the Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8 and plugins
        run: |
          pip install --upgrade pip==21.3.1
          python3.8 -m venv env
          source env/bin/activate
          pip install --upgrade pip==21.3.1
          pip install  lintly==0.6.0 flake8==4.0.1 flake8-bugbear==22.1.11 black==21.12b0 markupsafe==2.0.1
      - name: Run linter
        run: |
          source env/bin/activate
          flake8 --exclude env | lintly --format=flake8
          black . --exclude env --check 2>&1 >/dev/null | lintly    --format=black
      - name: clean venv
        run: |
          rm -r env
