name: tests

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:

jobs:

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    name: Tests
    # Name the Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install basic dependencies
        run: |
          pip install --upgrade pip
          pip install pytest-cov
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest --cache-clear --cov=pyrelational tests > pytest-coverage.txt
      - name: Print error
        if: failure()
        run: |
          cat pytest-coverage.txt
